#!/bin/bash -e

echo "--> Changing bash prompt"
cat /provision/bashrc-prompt >> ~/.bashrc

echo "--> Setting up database for testing"
if ! hash psql >/dev/null 2>&1; then
  log_ "psql is not in your path, is PostgreSQL installed?"
  exit 1
fi

echo "--> Setting up database"
cd /vagrant
cp ./environments/vagrant.env current.env
. ./current.env
sudo -u postgres psql -c "drop database $DB_NAME;" >/dev/null 2>&1 && true
sudo -u postgres psql -c "drop user $DB_USER;" >/dev/null 2>&1 && true
sudo -u postgres psql -c "create user $DB_USER with CREATEDB password '$DB_USER_PASSWORD';"
psql postgres -c "create database $DB_NAME;"
sudo -u postgres psql -c "alter role $DB_USER Superuser;"

echo "--> Setting up machine for development"
cd /vagrant
./setup-dev-env.sh
