language: node_js
node_js:
  - "6"
sudo: false
dist: trusty
cache:
  directories:
  - node_modules
branches:
  only:
  - master
services:
  - postgresql
before_install:
  - cd src
  - cp environments/travis.env current.env
  - . ./current.env
script: npm test
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
