language: node_js
node_js:
  - "6"
sudo: false
dist: trusty
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- cd src
- cp template.env env.env
env:
- NODE_ENV=development
script: npm test
after_script:
- npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
